### ISSUE TITLE
Add support to StreamType

### ISSUE THREAD

**Issue by PedroCorreiaLuis** [PedroCorreiaLuis/csv-parser#17]
Implement the `extractHeaders` and the `parsedCSV` in the Parser object so that this type is handled in those functions

**Comment by joao-penim** [comment]
In a Stream we are expecting each String to be a line?

**Comment by PedroCorreiaLuis** [comment]
> In a Stream we are expecting each String to be a line?

Lets assume that for: 
- IteratorType
- IterableType
- SeqType
- StreamType

Each String is a line
